[project]
name = "torch-starter"
version = "0.1.0"
description = "Optimized Deep Learning starter template with uv, CUDA 13.0 PyTorch, and VS Code Dev Containers."
requires-python = ">=3.12,<3.13"
license = { text = "MIT" }
authors = [{ name = "Your Name" }]
keywords = ["deep-learning", "pytorch", "transformers", "uv", "devcontainer"]

# Minimal core dependencies - only essentials for performance
dependencies = [
  # Deep learning core
  "transformers>=4.42,<5.0",
  "datasets>=2.19,<3.0",
  "accelerate>=0.31,<1.0",
  "safetensors>=0.4,<1.0",
  "torchvision>=0.21.0",
  "torchaudio>=2.6.0",
  "albumentations>=2.0.8",
  # Core scientific computing
  "numpy>=1.26,<2.0",
  "pandas>=2.0,<3.0",
  "scipy>=1.11,<2.0",
  # Machine learning essentials
  "scikit-learn>=1.3,<2.0",
  "tqdm"
  # Tokenization
  "sentencepiece",
  # Visualization (minimal)
  "matplotlib",
  "plotly",
  "seaborn",
  # Jupyter minimal
  "jupyter>=1.0,<2.0",
  "ipykernel>=6.29,<7.0",
  # Configuration and utilities
  "pyyaml>=6.0,<7.0",
  "requests>=2.32.0,<3.0",
  "viztracer>=0.17.1",
  # Environment management
  "python-dotenv>=1.0,<2.0",
  
]

# Development tools - minimal set
dev = [
  "ruff",
  "mypy",
  "pydantic",
  "pytest",
  "pytest-cov",
  "types-requests",
  "types-PyYAML",
  "pre-commit",
  "memory-profiler",
  "safety",
  "ruff",
  "mypy",
  "pytest",
  "pytest-cov",
]

# Extended data science tools (optional)
datascience = [
  "seaborn>=0.13,<1.0",
  "plotly>=5.0,<6.0",
  "scikit-image>=0.25.0,<1.0",
  "pywavelets>=1.9.0,<2.0",
]

# Notebook and lab tools (optional)
notebook = [
  "jupyterlab",
  "ipdb",
  "notebook",
]

# Experiment tracking (optional)
tracking = [
  "tensorboard",
  "wandb",
]

# Data acquisition (optional)
data = [
  "kaggle",
]

# Profiling tools (optional) 
profiling = [
  "viztracer",
  "memory-profiler",
]

# Security scanning (optional)
security = [
  "safety",
  "bandit",
]

[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["torch_starter"]

# Ruff configuration - optimized
[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = [
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    "notebooks/.ipynb_checkpoints"
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "C90", # mccabe complexity
    "S",   # flake8-bandit (security)
    "T20", # flake8-print
]
ignore = [
    "E501",  # Line too long (handled by formatter)
    "B008",  # Do not perform function calls in argument defaults
    "S101",  # Use of assert detected
    "T201",  # print found (allow in notebooks and scripts)
]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["torch_starter"]
force-single-line = false

[tool.ruff.format]
preview = true
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

# MyPy configuration - performance optimized
[tool.mypy]
python_version = "3.12"
strict = true
warn_unused_configs = true
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
pretty = true

# Performance optimizations
cache_dir = ".mypy_cache"
sqlite_cache = true
incremental = true

exclude = [
    "build/",
    "dist/", 
    "notebooks/",
    ".venv/",
    ".mypy_cache/",
    ".pytest_cache/",
    "__pycache__/"
]

# Skip type checking for heavy dependencies to improve performance
[[tool.mypy.overrides]]
module = [
    "torch.*",
    "torchvision.*", 
    "transformers.*",
    "datasets.*",
    "matplotlib.*",
    "seaborn.*",
    "plotly.*",
    "sklearn.*",
    "viztracer.*",
    "memory_profiler.*"
]
ignore_missing_imports = true

# Pytest configuration
[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "-ra",
    "--strict-markers",
    "--disable-warnings",
    "--tb=short"
]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Coverage configuration
[tool.coverage.run]
source = ["torch_starter"]
omit = [
    "*/tests/*",
    "*/test_*",
    "*/__pycache__/*",
    "*/verify_setup/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

# UV configuration
[tool.uv]
index-strategy = "unsafe-best-match"
resolution = "highest"
compile-bytecode = true
link-mode = "copy"
concurrent-downloads = 10

# Primary index: PyPI (default)
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true


